/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void testInit(void);
extern void testSetAboveMaxFreqFails(void);
extern void testSetBelowMinFreqFails(void);
extern void testWithinLimitsPasses(void);
extern void testHalfFrequencyDivisionIsCorrect(void);
extern void testThirdFrequencyDivisionIsCorrect(void);
extern void testDoubleFrequencyIsCorrect(void);
extern void testTrebleFrequencyIsCorrect(void);
extern void testAlterFrequencyIsCorrect(void);
extern void testSetDutyIsCorrect(void);

//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "strobe_test.c";
  UnityBegin();
  RUN_TEST(testInit, 0);
  RUN_TEST(testWithinLimitsPasses, 1);
  RUN_TEST(testSetAboveMaxFreqFails, 2);
  RUN_TEST(testSetBelowMinFreqFails, 3);
  RUN_TEST(testHalfFrequencyDivisionIsCorrect, 4);
  RUN_TEST(testThirdFrequencyDivisionIsCorrect, 5);
  RUN_TEST(testDoubleFrequencyIsCorrect, 6);
  RUN_TEST(testTrebleFrequencyIsCorrect, 7);
  RUN_TEST(testAlterFrequencyIsCorrect, 8);
  RUN_TEST(testSetDutyIsCorrect, 9);
  return (UnityEnd());
}
